# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2b43365ca91703ddfc420bdef4167f9c2bac054025b47e9b2794581b3095a0e97d2fbb88c759277b098458a6d99e251c04353ea029638c8dd3e631bb2070631

test:
  secret_key_base: 3b237bf8c5a33fc7cdf23e1816182a7f216801fab1de292a80c7fc2fe4e9b2d94364dbf81d960411aa816f247fdab177dc223c254c118a706e4a09c93257d44d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
